backend:
  name: github
  repo: rc-wuerenlos/wuerenlos.rugby


media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "player"
    label: "Player"
    folder: "content/players"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ" }
      - label: "Position"
        name: "positions"
        widget: "select"
        multiple: true
        options:
          - prop
          - hooker
          - lock
          - flanker
          - no 8
          - scrumhalf
          - flyhalf
          - insidecenter
          - outsidecenter
          - wing
          - fullback
      - label: Nationalities
        name: nationalities
        widget: "select"
        options:
          - switzerland
          - france
          - south africa
          - england
          - scotland
          - wales
      - { label: "Is Active", name: "active", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }